name: RSIslandManager
version: 5.0.0
main: com.rserene.chosen.server.rsislandmanager.RSIslandManager
api-version: 26.1
folia-supported: true
authors: [Chosen_1st]
commands:
  rim:
    usage: /rim <recipemenu|tips|slime>
    description: RSIslandManager 主命令
    permission: rsislandmanager.rim
    permission-message: §c你没有权限使用此命令

permissions:
  rsislandmanager.rim:
    default: true
    description: 允许使用 /rim 命令