
 name: RSIslandManager
 version: \${version}
 main: com.rserene.chosen.server.rsislandmanager.RSIslandManager
 api-version: 26.1
 folia-supported: true
 authors: [Chosen_1st]
 commands:
   Slime:
     usage: /Slime
     description: Look The Slime Chunk
     permission: rsislandmanager.slime
     permission-message: 你没有权限
     default: op
   Tips:
     usage: /Tips
     description: Look Tips
   Menu:
     usage: /Menu
     description: Open Menu
 scription: Open Menu
 